"""add merged_into_id to businesses

Revision ID: 45052d1fb492
Revises: e50cd84fded4
Create Date: 2026-09-09 18:12:20.053440
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45052d1fb492'
down_revision: Union[str, None] = 'e50cd84fded4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('merged_into_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_businesses_merged_into_id'), 'businesses', ['merged_into_id'], unique=False)
    op.create_foreign_key(None, 'businesses', 'businesses', ['merged_into_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_index(op.f('ix_businesses_merged_into_id'), table_name='businesses')
    op.drop_column('businesses', 'merged_into_id')
    # ### end Alembic commands ###
