"""initial schema

Revision ID: e50cd84fded4
Revises: 
Create Date: 2026-09-09 17:56:35.296562
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e50cd84fded4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Requerido por las columnas geográficas. En una BD limpia (Supabase, otro
    # host) esto habilita PostGIS; en la imagen Docker ya viene habilitado.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chains',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('careers_url', sa.Text(), nullable=True),
    sa.Column('ats_type', sa.String(length=50), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chains_normalized_name'), 'chains', ['normalized_name'], unique=False)
    op.create_geospatial_table('geographic_zones',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('municipality', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('center', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('radius_m', sa.Integer(), nullable=True),
    sa.Column('polygon', Geography(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_geographic_zones_center', 'geographic_zones', ['center'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_geographic_zones_polygon', 'geographic_zones', ['polygon'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('source_requests',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=True),
    sa.Column('response_cached', sa.Boolean(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_requests_provider'), 'source_requests', ['provider'], unique=False)
    op.create_index(op.f('ix_source_requests_request_hash'), 'source_requests', ['request_hash'], unique=False)
    op.create_table('businesses',
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('primary_category', sa.String(length=100), nullable=True),
    sa.Column('secondary_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('chain_id', sa.BigInteger(), nullable=True),
    sa.Column('food_type', sa.String(length=150), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_range', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_source', sa.String(length=100), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_chain_id'), 'businesses', ['chain_id'], unique=False)
    op.create_index(op.f('ix_businesses_normalized_name'), 'businesses', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_businesses_primary_category'), 'businesses', ['primary_category'], unique=False)
    op.create_table('scans',
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('strategy', sa.String(length=20), nullable=True),
    sa.Column('area_covered', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['geographic_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_zone_id'), 'scans', ['zone_id'], unique=False)
    op.create_table('business_contacts',
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_contacts_business_id'), 'business_contacts', ['business_id'], unique=False)
    op.create_table('business_hours',
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_hours_business_id'), 'business_hours', ['business_id'], unique=False)
    op.create_geospatial_table('business_locations',
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('full_address', sa.Text(), nullable=True),
    sa.Column('colonia', sa.String(length=200), nullable=True),
    sa.Column('municipality', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=200), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('geog', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('map_url', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_place_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_business_locations_geog', 'business_locations', ['geog'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_business_locations_business_id'), 'business_locations', ['business_id'], unique=False)
    op.create_index(op.f('ix_business_locations_provider_place_id'), 'business_locations', ['provider_place_id'], unique=False)
    op.create_table('business_snapshots',
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_snapshots_business_id'), 'business_snapshots', ['business_id'], unique=False)
    op.create_table('business_sources',
    sa.Column('business_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_place_id', sa.String(length=200), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_place_id', name='uq_source_provider_place')
    )
    op.create_index(op.f('ix_business_sources_business_id'), 'business_sources', ['business_id'], unique=False)
    op.create_table('jobs',
    sa.Column('business_id', sa.BigInteger(), nullable=True),
    sa.Column('chain_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('title_category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('salary_period', sa.String(length=20), nullable=True),
    sa.Column('schedule', sa.String(length=150), nullable=True),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experience', sa.String(length=150), nullable=True),
    sa.Column('education', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('modality', sa.String(length=50), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_business_id'), 'jobs', ['business_id'], unique=False)
    op.create_index(op.f('ix_jobs_chain_id'), 'jobs', ['chain_id'], unique=False)
    op.create_index(op.f('ix_jobs_title_category'), 'jobs', ['title_category'], unique=False)
    op.create_table('match_log',
    sa.Column('business_a', sa.BigInteger(), nullable=True),
    sa.Column('business_b', sa.BigInteger(), nullable=True),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_a'], ['businesses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_b'], ['businesses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_log_business_a'), 'match_log', ['business_a'], unique=False)
    op.create_index(op.f('ix_match_log_business_b'), 'match_log', ['business_b'], unique=False)
    op.create_table('job_snapshots',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_snapshots_job_id'), 'job_snapshots', ['job_id'], unique=False)
    op.create_table('job_sources',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_sources_job_id'), 'job_sources', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_sources_job_id'), table_name='job_sources')
    op.drop_table('job_sources')
    op.drop_index(op.f('ix_job_snapshots_job_id'), table_name='job_snapshots')
    op.drop_table('job_snapshots')
    op.drop_index(op.f('ix_match_log_business_b'), table_name='match_log')
    op.drop_index(op.f('ix_match_log_business_a'), table_name='match_log')
    op.drop_table('match_log')
    op.drop_index(op.f('ix_jobs_title_category'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_chain_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_business_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_business_sources_business_id'), table_name='business_sources')
    op.drop_table('business_sources')
    op.drop_index(op.f('ix_business_snapshots_business_id'), table_name='business_snapshots')
    op.drop_table('business_snapshots')
    op.drop_index(op.f('ix_business_locations_provider_place_id'), table_name='business_locations')
    op.drop_index(op.f('ix_business_locations_business_id'), table_name='business_locations')
    op.drop_geospatial_index('idx_business_locations_geog', table_name='business_locations', postgresql_using='gist', column_name='geog')
    op.drop_geospatial_table('business_locations')
    op.drop_index(op.f('ix_business_hours_business_id'), table_name='business_hours')
    op.drop_table('business_hours')
    op.drop_index(op.f('ix_business_contacts_business_id'), table_name='business_contacts')
    op.drop_table('business_contacts')
    op.drop_index(op.f('ix_scans_zone_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_businesses_primary_category'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_normalized_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_chain_id'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_source_requests_request_hash'), table_name='source_requests')
    op.drop_index(op.f('ix_source_requests_provider'), table_name='source_requests')
    op.drop_table('source_requests')
    op.drop_geospatial_index('idx_geographic_zones_polygon', table_name='geographic_zones', postgresql_using='gist', column_name='polygon')
    op.drop_geospatial_index('idx_geographic_zones_center', table_name='geographic_zones', postgresql_using='gist', column_name='center')
    op.drop_geospatial_table('geographic_zones')
    op.drop_index(op.f('ix_chains_normalized_name'), table_name='chains')
    op.drop_table('chains')
    # ### end Alembic commands ###
